MACHINE = "imx93-11x11-lpddr4x-evk"
require conf/machine/include/oeros-edgeai-imx.inc
require conf/fragments/ros-lyrical.conf
require conf/fragments/edgeai.conf
BB_CONF_FRAGMENT_SUMMARY = "MACHINE imx93-11x11-lpddr4x-evk with imx Edge AI stack"
BB_CONF_FRAGMENT_DESCRIPTION = "MACHINE imx93-11x11-lpddr4x-evk with imx Edge AI stack."
