BB_CONF_FRAGMENT_SUMMARY = "MACHINE am68-sk with ti Edge AI stack"
BB_CONF_FRAGMENT_DESCRIPTION = "MACHINE am68-sk with ti Edge AI stack."
MACHINE = "am68-sk"
require conf/machine/include/oeros-edgeai-ti.inc
require conf/fragments/oeros/ros-lyrical.conf
require conf/fragments/oeros/edgeai.conf
