MACHINE = "am62axx-evk"
require conf/machine/include/oeros-edgeai-ti.inc
require conf/fragments/ros-lyrical.conf
require conf/fragments/edgeai.conf
BB_CONF_FRAGMENT_SUMMARY = "MACHINE am62axx-evk with ti Edge AI stack"
BB_CONF_FRAGMENT_DESCRIPTION = "MACHINE am62axx-evk with ti Edge AI stack."
