MACHINE = "intel-corei7-64"
require conf/machine/include/oeros-edgeai-intel.inc
require conf/fragments/ros-jazzy.conf
require conf/fragments/edgeai.conf
MACHINE_FEATURES:append = " edgeai-robotics-ai-suite"
BB_CONF_FRAGMENT_SUMMARY = "MACHINE intel-corei7-64 with intel Edge AI + Robotics AI Suite (ROS 2 Jazzy)"
BB_CONF_FRAGMENT_DESCRIPTION = "MACHINE intel-corei7-64 with intel Edge AI + Robotics AI Suite (ROS 2 Jazzy)."
