MACHINE = "intel-corei7-64"
require conf/machine/include/oeros-edgeai-intel.inc
require conf/fragments/ros-lyrical.conf
require conf/fragments/edgeai.conf
BB_CONF_FRAGMENT_SUMMARY = "MACHINE intel-corei7-64 with intel Edge AI stack"
BB_CONF_FRAGMENT_DESCRIPTION = "MACHINE intel-corei7-64 with intel Edge AI stack."
