MACHINE = "jetson-orin-nano-devkit"
require conf/machine/include/oeros-edgeai-tegra.inc
require conf/fragments/ros-lyrical.conf
require conf/fragments/edgeai.conf
BB_CONF_FRAGMENT_SUMMARY = "MACHINE jetson-orin-nano-devkit with tegra Edge AI stack"
BB_CONF_FRAGMENT_DESCRIPTION = "MACHINE jetson-orin-nano-devkit with tegra Edge AI stack."
