# Copyright (c) 2026 Wind River Systems, Inc.

BB_CONF_FRAGMENT_SUMMARY = "Limit build resource usage to keep the build host responsive"
BB_CONF_FRAGMENT_DESCRIPTION = "Limit build resource usage to keep the build host responsive \
  - Raises the bitbake process nice level and sets CPU/IO/memory pressure thresholds bitbake will \
    throttle new tasks against. Useful on a shared or resource-constrained build host. \
"

BB_NICE_LEVEL = "11"
BB_PRESSURE_MAX_CPU = "1000000"
BB_PRESSURE_MAX_IO = "50000"
BB_PRESSURE_MAX_MEMORY = "5000"
