# Copyright (c) 2026 Wind River Systems, Inc.

SUMMARY = "OEROS container image holding the ros2-image-sdktest cross SDK"
DESCRIPTION = "The cross toolchain produced by 'bitbake ros2-image-sdktest \
-c populate_sdk', packaged as a container that runs on the SDK host \
architecture and builds for MACHINE.  Run it on a workstation and colcon \
build against the target sysroot without installing anything locally."

require oeros-container-image.inc

inherit ros_distro_${ROS_DISTRO}

# This image is the SDK and nothing else.
#
# It cannot layer onto oeros-container-base, because whenever the SDK is a
# genuine cross SDK the base image is the target architecture and the
# toolchain is not.  Instead the nativesdk sysroot inside the SDK -- which
# carries its own glibc, bash, python3 and coreutils -- is the whole userland.
OCI_BASE_IMAGE = ""
IMAGE_INSTALL = ""
IMAGE_FEATURES = ""
NO_RECOMMENDATIONS = "1"
PACKAGE_INSTALL = ""

# image-oci derives the architecture from TARGET_ARCH, which is the wrong end
# of a cross SDK: the container runs on the SDK host.
OCI_IMAGE_ARCH = "${@oe.go.map_arch(d.getVar('SDK_ARCH'))}"

# create_shar deletes ${TOOLCHAIN_OUTPUTNAME}.${SDK_ARCHIVE_TYPE} once it has
# appended it to the self-extracting installer, so the plain archive only
# survives when the shar step is disabled.  The SDK multiconfigs do that with
#     SDK_PACKAGING_FUNC:pn-ros2-image-sdktest = ""
OEROS_SDK_IMAGE = "ros2-image-sdktest"
do_rootfs[depends] += "${OEROS_SDK_IMAGE}:do_populate_sdk"

# The SDK is built against SDKPATH as a hardcoded prefix and normally has to
# be relocated on install.  A container is a filesystem we control completely,
# so unpacking it at exactly that path makes relocation unnecessary and leaves
# every interpreter path, CMake toolchain file and environment-setup script
# already correct.
OEROS_SDK_INSTALL_PATH = "${SDKPATH}"

ROOTFS_POSTPROCESS_COMMAND += "oeros_container_install_sdk ; "
oeros_container_install_sdk () {
    sdk_archive=$(ls -1 ${SDK_DEPLOY}/oecore-*${OEROS_SDK_IMAGE}*-${MACHINE}-toolchain-*.${SDK_ARCHIVE_TYPE} 2>/dev/null | head -n 1)
    if [ -z "$sdk_archive" ]; then
        bbfatal "No ${OEROS_SDK_IMAGE} SDK archive in ${SDK_DEPLOY}. Build it first with" \
                "'bitbake ${OEROS_SDK_IMAGE} -c populate_sdk' in this multiconfig, and check that" \
                "SDK_PACKAGING_FUNC:pn-${OEROS_SDK_IMAGE} is empty so the archive is kept."
    fi
    bbnote "Unpacking $sdk_archive into ${OEROS_SDK_INSTALL_PATH}"

    install -d ${IMAGE_ROOTFS}${OEROS_SDK_INSTALL_PATH}
    tar -xf "$sdk_archive" -C ${IMAGE_ROOTFS}${OEROS_SDK_INSTALL_PATH}

    # Give the container the handful of top level paths a runtime expects,
    # pointed at the SDK's own nativesdk sysroot.
    sdk_native_sysroot=$(cd ${IMAGE_ROOTFS}${OEROS_SDK_INSTALL_PATH}/sysroots && ls -1d *-oesdk-linux 2>/dev/null | head -n 1)
    if [ -z "$sdk_native_sysroot" ]; then
        bbfatal "No nativesdk sysroot under ${OEROS_SDK_INSTALL_PATH}/sysroots"
    fi
    sdk_native_sysroot="${OEROS_SDK_INSTALL_PATH}/sysroots/$sdk_native_sysroot"

    install -d ${IMAGE_ROOTFS}/bin ${IMAGE_ROOTFS}/usr/bin ${IMAGE_ROOTFS}/tmp
    chmod 1777 ${IMAGE_ROOTFS}/tmp
    ln -sf "$sdk_native_sysroot/bin/sh"   ${IMAGE_ROOTFS}/bin/sh
    ln -sf "$sdk_native_sysroot/bin/bash" ${IMAGE_ROOTFS}/bin/bash
    ln -sf "$sdk_native_sysroot/bin/env"  ${IMAGE_ROOTFS}/usr/bin/env

    # environment-setup-* is what the SDK expects to be sourced; the ROS
    # environment inside the target sysroot comes with it.
    cat > ${IMAGE_ROOTFS}/ros_entrypoint.sh <<SDKEOF
#!/bin/sh
# Generated by oeros-container-sdk-cross.bb
set -e
for env_setup in ${OEROS_SDK_INSTALL_PATH}/environment-setup-*; do
    if [ -f "\$env_setup" ]; then
        set +e
        . "\$env_setup"
        set -e
    fi
done
if [ "\$#" -eq 0 ]; then
    exec /bin/bash
fi
exec "\$@"
SDKEOF
    chmod 0755 ${IMAGE_ROOTFS}/ros_entrypoint.sh
}

OCI_IMAGE_ENTRYPOINT = "/ros_entrypoint.sh"
OCI_IMAGE_CMD = "/bin/bash"
OCI_IMAGE_WORKINGDIR = "/workspace"
OCI_IMAGE_LABELS:append = " io.oeros.sdk=cross io.oeros.sdk-host-arch=${SDK_ARCH}"
