BB_CONF_FRAGMENT_SUMMARY = "Enable meta-oeros Edge AI packagegroups in images"
BB_CONF_FRAGMENT_DESCRIPTION = "Enable meta-oeros Edge AI packagegroups in images."
DISTRO_FEATURES:append = " edgeai"
IMAGE_INSTALL:append = " packagegroup-oeros-edgeai"
