## SUMMARY: MACHINE am69-sk with ti Edge AI stack
MACHINE = "am69-sk"
require conf/machine/include/oeros-edgeai-ti.inc
require conf/fragments/oeros/ros-lyrical.conf
require conf/fragments/oeros/edgeai.conf
