## SUMMARY: MACHINE imx8mp-lpddr4-evk with imx Edge AI stack
MACHINE = "imx8mp-lpddr4-evk"
require conf/machine/include/oeros-edgeai-imx.inc
require conf/fragments/oeros/ros-lyrical.conf
require conf/fragments/oeros/edgeai.conf
