## SUMMARY: MACHINE jetson-orin-nano-devkit-super with tegra Edge AI stack
MACHINE = "jetson-orin-nano-devkit-super"
require conf/machine/include/oeros-edgeai-tegra.inc
require conf/fragments/oeros/ros-lyrical.conf
require conf/fragments/oeros/edgeai.conf
