## SUMMARY: MACHINE intel-corei7-64 with intel Edge AI stack
MACHINE = "intel-corei7-64"
require conf/machine/include/oeros-edgeai-intel.inc
require conf/fragments/oeros/ros-lyrical.conf
require conf/fragments/oeros/edgeai.conf
